name: Production Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and Build Frontend
        working-directory: ./app
        run: |
          npm ci
          npm run build:production
        env:
          REACT_APP_WS_URL: 'wss://soulsanctuary.cloud/ws'
          REACT_APP_API_URL: 'https://soulsanctuary.cloud/api'
          REACT_APP_SOLANA_NETWORK: 'mainnet-beta'
          REACT_APP_SOLANA_RPC_HOST: ${{ secrets.REACT_APP_SOLANA_RPC_HOST }}

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: '152.42.184.16'
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app/build/*,server/*"
          target: "/var/www/soulsanctuary"
          strip_components: 1

      - name: Execute Deployment Commands
        uses: appleboy/ssh-action@master
        with:
          host: '152.42.184.16'
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Deploy frontend
            rm -rf /var/www/html/*
            cp -r /var/www/soulsanctuary/build/* /var/www/html/
            
            # Deploy backend
            cd /var/www/soulsanctuary/server
            npm ci --production
            pm2 restart soul-sanctuary || pm2 start src/server.js --name soul-sanctuary --env production
            pm2 save
