name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Check SSH Connection
        run: ssh -v root@${{ secrets.DROPLET_IP }} 'echo "SSH Connection Successful"'

      - name: Deploy to DigitalOcean
        run: |
          ssh root@${{ secrets.DROPLET_IP }} '
            set -e
            echo "Starting deployment..."
            cd /var/www/soulsanctuary || exit 1
            echo "Current directory: $(pwd)"
            echo "Fetching latest changes..."
            git fetch origin master
            git reset --hard origin/master
            echo "Installing dependencies..."
            cd server || exit 1
            npm install
            echo "Restarting server..."
            pm2 restart soulsanctuary-backend || pm2 start src/server.js --name soulsanctuary-backend
            echo "Deployment completed successfully"
          '
