name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            set -e
            echo "Starting deployment..."
            cd /var/www/soulsanctuary || exit 1
            echo "Current directory: $(pwd)"
            echo "Fetching latest changes..."
            git fetch origin master
            git reset --hard origin/master
            echo "Installing dependencies..."
            cd server || exit 1
            npm install
            echo "Restarting server..."
            pm2 restart soulsanctuary-backend || pm2 start src/server.js --name soulsanctuary-backend
            echo "Deployment completed successfully"
