name: Deploy to DigitalOcean
on:
  push:
    branches: 
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          cd app && npm install
        
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: List DigitalOcean apps
        run: doctl apps list
          
      - name: Deploy to DigitalOcean App Platform
        run: |
          echo "Listing available apps..."
          doctl apps list
          
          echo "Getting app ID..."
          APP_ID=$(doctl apps list --format ID --no-header | head -n 1)
          
          if [ -z "$APP_ID" ]; then
            echo "Error: Could not find app ID"
            exit 1
          fi
          
          echo "Found app ID: $APP_ID"
          echo "Creating deployment..."
          doctl apps create-deployment $APP_ID --wait
          
          echo "Deployment completed"
