name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install Root Dependencies
        run: npm install --legacy-peer-deps
          
      - name: Install and Build App
        env:
          NODE_ENV: production
          CI: false
          HOST: soulsanctuary.cloud
          PORT: 8080
          API_VERSION: v1
          CORS_ORIGIN: https://soulsanctuary.cloud
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          REACT_APP_API_URL: https://soulsanctuary.cloud
          REACT_APP_WS_URL: wss://soulsanctuary.cloud
        run: |
          cd app
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps --force
          npm install --save ajv@8.12.0 ajv-keywords@5.1.0 ajv-formats@2.1.1 schema-utils@4.2.0
          NODE_OPTIONS="--max-old-space-size=4096" DISABLE_ESLINT_PLUGIN=true npm run build
          
          cd soulmate/server
          npm install --legacy-peer-deps
          cd ../..
          cd ..
          
      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@main
        with:
          app_name: ${{ secrets.DIGITALOCEAN_APP_NAME }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: |
            [
              {
                "name": "soul-sanctuary",
                "registry": "registry.digitalocean.com",
                "repository": "soul-sanctuary",
                "tag": "${{ github.sha }}"
              }
            ]
