name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Dependencies
        run: |
          npm install
          cd app && npm install
        
      - name: Build
        working-directory: ./app
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
        run: npm run build
          
      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@main
        with:
          app_name: soul-sanctuary
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: |
            [
              {
                "name": "soul-sanctuary",
                "registry": "registry.digitalocean.com",
                "repository": "soul-sanctuary",
                "tag": "${{ github.sha }}"
              }
            ]
